### ISSUE TITLE
баг

### ISSUE THREAD

**Issue by Lenchik** [cuprum/AkelPad_coders#1]
![clipboard-3](https://cloud.githubusercontent.com/assets/2931130/6150215/1a5086ac-b21f-11e4-9276-608d9566842a.png)
на картинке видно что неправильно подсвечивается, а также зачем-то включается фолдинг, когда фолдится нечему

**Comment by cuprum** [comment]
Про подсветку:
- подсветку ссылок поправлю
- по поводу подсветки дефисов. Согласно синтаксису, чтобы нарисовать линию достаточно трех "-", остальные лишние, вот и не подсвечиваются

Про фолдинг.
Если я все понял, для любого файла, у которого подразумевается фолдинг, окошко CodeFold все-равно появляется, даже если файл пустой.

**Comment by cuprum** [comment]
Про линию беру слова обратно. Говорится о трех и  более.

**Comment by Lenchik** [comment]
Да, оказывается, про фолдинг именно так, как вы говорите.
Я момент с линией даже и не заметил :) Регэкспами решается, наверное.

https://github.com/h5bp/html5-boilerplate/blob/master/README.md
https://github.com/AndreyAkinshin/Russian-Phd-LaTeX-Dissertation-Template/blob/master/README.md
https://github.com/AvsPmod/AvsPmod/blob/master/README.md

На этих ещё имеет смысл потестить ;)

**Comment by Lenchik** [comment]
https://github.com/h5bp/html5-boilerplate/blob/master/README.md
https://github.com/AndreyAkinshin/Russian-Phd-LaTeX-Dissertation-Template/blob/master/README.md

На этих ещё имеет смысл потестить ;)
